package com.yaksh.user_security.Exception;

public enum ErrorCode {
    USER_ALREADY_EXISTS,
    INVALID_EMAIL,
    USER_NOT_FOUND,
    INVALID_PASSWORD,
    OTP_EXPIRED, INVALID_OTP, USER_ALREADY_VERIFIED, ACCOUNT_NOT_VERIFIED, BAD_CREDENTIALS, DATA_NOT_FOUND,
    REVIEW_TOO_SHORT, ACCOUNT_BANNED, INAPPROPRIATE_REVIEW

}
